# Site settings
title: Jordacity Underground
email: jordacity@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  You should not be reading this. If you are, congratulations, there are no real secrets here. 
  This is merely a backdoor into my mind and my current projects. It's like the lens of the camera facing the canvas that contains all my 
  works in progress, before they get wheeled to my front door for public presentation. Is it a privilege to be here? 
  Or just a waste of time? That's for you to decide. For now, enjoy the ride. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jorda.city" # the base hostname & protocol for your site
twitter_username: splenda_daddy
github_username:  jfglobal

# Build settings
markdown: kramdown
